<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>Umbraco Semantic Search Qdrant Provider</Title>
        <RootNamespace>Fynydd.Umbraco.Search.Qdrant</RootNamespace>

        <AssemblyVersion>17.0.1</AssemblyVersion>
        <FileVersion>17.0.1</FileVersion>
        <PackageVersion>17.0.1</PackageVersion>

        <PackageId>fynydd.umbraco.search.qdrant</PackageId>
        <Authors>Fynydd LLC</Authors>
        <Company>Fynydd LLC</Company>
        <Description>Qdrant vector store support for Umbraco semantic search.</Description>
        <Copyright>Copyright (c) 2026 Fynydd LLC</Copyright>
        <PackageTags>umbraco;qdrant;semantic-search;vector-search</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageReleaseNotes>Updated packages.</PackageReleaseNotes>
        <PackageIcon>nuget-icon.png</PackageIcon>
        <PackageOutputPath>nupkg</PackageOutputPath>
        <PackageProjectUrl>https://github.com/fynydd/Fynydd.Umbraco.Search.Qdrant</PackageProjectUrl>
        <RepositoryUrl>https://github.com/fynydd/Fynydd.Umbraco.Search.Qdrant</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Qdrant.Client" Version="1.19.0" />
        <PackageReference Include="ReverseMarkdown" Version="6.1.1" />
        <PackageReference Include="Umbraco.AI.Search" Version="17.0.1" />
    </ItemGroup>

    <ItemGroup>
        <!-- These override Umbraco dependencies with security vulnerabilities -->
        <PackageReference Include="Microsoft.OpenApi" Version="3.9.0" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
        <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
        <PackageReference Include="MessagePack.AspNetCoreMvcFormatter" Version="3.1.8" />
    </ItemGroup>

    <ItemGroup>
        <None Include="nuget-icon.png" Pack="true" PackagePath="" CopyToOutputDirectory="Always" />
        <None Include="appsettings-schema.Umbraco.Search.Qdrant.json" Pack="true" PackagePath="contentFiles/any/any/;content/" CopyToOutputDirectory="Always" />
        <None Include="..\README.md" Pack="true" PackagePath="" CopyToOutputDirectory="Always" />
        <None Include="..\LICENSE.txt" Pack="true" PackagePath="" CopyToOutputDirectory="Always" />
    </ItemGroup>
    
</Project>
